/guides/source直下の英文ソースをrails/railsのv6.1.3.1タグのものに差し替える
yasslab/railsguides.jp pull request #1031
Opened 2021-04-16 13:25 UTC by hachi8833

## 変更内容

以下の変更を行います。

### 1. 英文ソースの更新

Rails 6.1.3.1対応のため、英文ソースをv6.1.3.1タグのものに更新しました。

### 2. 英文ソースで増えたファイルを日本語版にコピー

英文ソースから以下にコピーしました。

* guides/source/ja/action_view_helpers.md

### 3. 不要な日本語版ソースの削除

英語版から既になくなっている以下の未使用ソースを日本語版から削除しました。

* guides/source/ja/constant_autoloading_and_reloading.md
* guides/source/ja/nested_model_forms.md
* guides/source/ja/profiling.md

### 4. documents.yamlの更新

Zeitverkモード以前のclassicモードのドキュメントが現在のRailsガイドに表示されていないので、[documents.yamlを更新しました](https://github.com/yasslab/railsguides.jp/compare/master...yasslab:update_en_source_to_6.1.3.1?expand=1#diff-97974735b437fef95bd5b7d3aa2153c598a6727d401014d05c5b14b32f21d8c9L153)。

* guides/source/ja/autoloading_and_reloading_constants_classic_mode.md

## v6.1->v6.1.3.1の差分について

ほぼすべてのファイルで更新が入っていますが、大半はリポジトリURLの`master`->`main`の変更や、微細な修正のようです。

ただ、v6->v6.1ではリリースノートとアップグレードガイド以外の差分のキャッチアップも必要なので、合わせてチェック・反映します🙇。

## Webpacker/Concernsについて

* Concernsは[Getting Started](https://guides.rubyonrails.org/getting_started.html#using-concerns)ガイドに含まれているので、本プルリクをマージいただいた後で更新翻訳します。
* [Webpackerガイド](https://edgeguides.rubyonrails.org/webpacker.html)は、惜しくもv6.1.3.1にはまだ含まれていませんでした。これとは別のプルリクで臨時に追加する形にしようかと思いますが、いかがでしょう？ @yasulab  

## 変更情報

* 引用元タグ: v6.1.3.1
* 引用元コミット: 85c6823b77
* 引用元URL: https://github.com/rails/rails/tree/v6.1.3.1/guides/source

### 参考:前回6.1のときの更新情報: #1005

* 引用元タグ: v6.1.0
* 引用元コミット: 914caca2d3
* 引用元URL: https://github.com/rails/rails/tree/v6.1.0/guides/source

2021-04-16 13:33 UTC, yasulab requested changes
@hachi8833 

> 3. 不要な日本語版ソースの削除

こちら検索のインデックス作成などで齟齬が発生しそうなので（検証しながら対応する必要がありそうなので）、ファイル削除に関するコミットについては別 PR にしていただけると嬉しいです! 🙏 

> 4. documents.yamlの更新

こちらは下記のリンクを使っており、意図的に目次に追加していないカタチを採っておりますので、追加しないでもらえると助かります...!! 🙏 

![image](https://user-images.githubusercontent.com/155807/115031600-541f7c80-9f03-11eb-9d80-8b972b26b131.png)



> * [Webpackerガイド](https://edgeguides.rubyonrails.org/webpacker.html)は、惜しくもv6.1.3.1にはまだ含まれていませんでした。これとは別のプルリクで臨時に追加する形にしようかと思いますが、いかがでしょう？ @yasulab

はい！良いと思います！(๑•̀ㅂ•́)و✨

2021-04-16 13:41 UTC, hachi8833 commented
@yasulab 

documents.yamlの変更と、日本語ソースの削除をそれぞれ取り消しました🙇

2021-04-16 13:44 UTC, yasulab commented
@hachi8833 早速のご対応ありがとうございます！😻🆒✨ マージしますね！🛠💨✨

2021-04-16 13:45 UTC, yasulab commented
（CI は落ちてますがマージ後、別途対応します！🛠💨✨）

https://travis-ci.org/github/yasslab/railsguides.jp/builds/767272045#L492-L496

2021-04-16 13:45 UTC, merged

2021-04-18 00:46 UTC, yasulab commented on guides/source/ja/documents.yaml
> -    -
Syntax エラーでした...!! 😱 💦 
修正しました! 🛠💨✨ https://github.com/yasslab/railsguides.jp/commit/6975695d221a300cfa0da884ef14bc87d8178a5a

2021-04-18 01:18 UTC, yasulab commented on guides/source/ja/documents.yaml
> -    -
このようなミスがあったときにもテストで自動で検知できるようにしておきました (๑•̀ㅂ•́)و✨

cf. #1034 [DON'T MERGE] Check documents yaml syntax in CI