水平シャーディングの翻訳追加
yasslab/railsguides.jp pull request #1076
Opened 2021-09-06 06:27 UTC by shunshunsuke

resolve #1066

ver6.1で追加された水平シャーディング機能のドキュメントを追加しました。
翻訳対象:
https://github.com/yasslab/railsguides.jp/blob/master/guides/source/active_record_multiple_databases.md

localでビルドして動作確認済みです。

2021-09-06 06:28 UTC, yasulab commented
PR ありがとうございます！ひとまず CI を `Approve and run` では知らせておきますね！🤖💨✨

2021-09-06 09:27 UTC, hachi8833 requested changes
@shunshunsuke 追加翻訳ありがとうございます！コメント確認お願いします🙏。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +メモ：Railsはどのデータベースがレプリカなのか知らないので、完了したらこれを抽象クラスに追加する必要があります。
スタイルを統一。

> Note: Railsはどのデータベースがレプリカなのか知らないので、完了したらこれを抽象クラスに追加する必要があります。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +Railsは新しいクラスを一度だけ生成します。新しいscaffoldsによって上書きされることはなく、scaffoldが削除されたときには削除されます。
スタイルを統一。

> Railsは新しいクラスを一度だけ生成します。これは新しいscaffoldsによって上書きされることはなく、scaffoldが削除されると削除されます。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +`AnimalsRecord`と異なる既存の抽象クラスがある場合、`--parent`オプションを利用して別の抽象クラスを指定することができます。
スタイルを統一。

> `AnimalsRecord`と異なる既存の抽象クラスがある場合、`--parent`オプションで別の抽象クラスを指定できます。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +このような場合、別の親クラスを利用することを指定しているため、`AnimalsRecord`の生成をスキップします。
スタイルを統一。

>上では別の親クラスを利用することを指定しているため、`AnimalsRecord`の生成をスキップします。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +Railsで水平シャーディングをサポートするためのAPIは、Rails6.0以降の複数データベース/垂直シャーディングAPIに似ています。
スタイルを統一。

> Railsで水平シャーディングをサポートするAPIは、Rails 6.0以降の複数データベースや垂直シャーディングAPIに似ています。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +シャードは、次のように3層構成で宣言されます:
スタイルを統一。

> シャードは、次のように3層（3-tier）構成で宣言されます。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +次に、モデルは `shards`キーを介して`connects_to`APIに接続されます:
スタイルを統一。

> 次に、モデルは`shards`キーを介して`connects_to`APIに接続されます。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +これを行うには、database.ymlを以下のように2-tierから3-tier設定に変更する必要があります。
スタイルを統一。

> これを行うには、database.ymlを以下のように2層（2-tier）設定から3層（3-tier）設定に変更する必要があります。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +その後、モデルは`connected_to`APIを使って手動でコネクションを切り替えることができます。 シャーディングを使用する場合は、`role`と`shard`の両方を渡す必要があります。
スタイルを統一。

> これで、モデルは`connected_to`APIを用いて手動でコネクションを切り替えられるようになります。 シャーディングを使う場合は、`role`と`shard`の両方を渡す必要があります。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +水平シャーディングAPIはリードレプリカもサポートしています。`connected_to`APIでロールとシャードを入れ替えることができます。
スタイルを統一。

> 水平シャーディングAPIはリードレプリカ（read replica）もサポートしています。以下のように`connected_to` APIでロールやシャードを切り替えられます。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +## 細かなデータベース接続切り替え
> ## 粒度の細かいデータベース接続切り替え

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +Rails 6.1では、すべてのデータベースに対してグローバルにコネクションを切り替えるのではなく、1つのデータベースに対してコネクションを切り替えることができます。この機能を使うには、まずアプリケーションの設定で`config.active_record.legacy_connection_handling`を`false`に設定する必要があります。パプリックAPIは同じ動作をするので、ほとん
スタイルを統一。

> Rails 6.1では、すべてのデータベースでグローバルにコネクションを切り替えるのではなく、1つのデータベースでコネクションを切り替えることが可能です。この機能を使うには、まずアプリケーションの設定で`config.active_record.legacy_connection_handling`を`false`に設定する必要があります。パプリックAPIの振る舞いは変わらないので、その他の変更はほとんどのアプリケーションで不要です。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +`legacy_connection_handling`をfalseに設定すると、抽象的な接続クラスでも他のコネクションに影響を与えずにコネクションを切り替えることができます。これは、`ApplicationRecord`のクエリがプライマリに送られることを保証しつつ、`AnimalsRecord`のクエリをレプリカから読み込むように切り替えるときに便利です。
スタイルを統一。

> `legacy_connection_handling`を`false`に設定すると、任意の抽象コネクションクラスで他のコネクションに影響を与えずにコネクションを切り替えられます。これは、`ApplicationRecord`のクエリがプライマリに送信されることを保証しつつ、`AnimalsRecord`のクエリをレプリカから読み込むように切り替えるときに便利です。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +また、シャードに対して細かく接続をスワップできます。
スタイルを統一。

> 以下のようにシャードに対して接続を細かな粒度で切り替えることも可能です。

2021-09-06 09:27 UTC, hachi8833 commented on guides/source/ja/active_record_multiple_databases.md
> +primaryデータベースクラスタのみを切り替えたい場合は`ApplicationRecord`を使用してください:
スタイルを統一。

> primaryデータベースクラスタのみを切り替えたい場合は、以下のように`ApplicationRecord`を使います。

2021-09-10 02:19 UTC, yasulab commented
@shunshunsuke よければ @hachi8833 さんからの上記 Request Changes を自分の方で取り込んでおこうかなと考えていますが、いかがでしょう? 👀💭 よければ自分の方で作業しちゃいますね! 🛠💨✨

2021-09-10 06:01 UTC, shunshunsuke commented
@yasulab 
すみません、よろしくお願いいたします。 🙇

2021-09-10 06:07 UTC, yasulab commented
@shunshunsuke 全然大丈夫です！😆👌✨ では残りの作業は自分の方で対応しますね！🛠💨✨ cc/ @hachi8833

2021-09-10 11:16 UTC, merged

2021-09-10 11:17 UTC, yasulab commented
こちら自分の方で残りの作業を対応しておきました！後ほど本番環境にデプロイしますね！🚀✨ cc/ @shunshunsuke @hachi8833